site_name: Piracy Link Archive
copyright: Made by Zenith Rifle and Vran29. Huge thanks to fmhy!
theme:
  name: material
  icon:
    logo: material/pirate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

nav:
  - ğŸ´â€â˜ ï¸Home: "index.md"
  - ğŸ¬Movies: "Movies.md"
  - ğŸ“ºTV Shows: "TV-Shows.md"
  - ğŸ§Music: "Music.md"
  - ğŸ®Games: "Games.md"
  - ğŸ’½Software: "Software.md"
  - ğŸ“šComics: "Comics.md"
  - ğŸï¸Manga: "Manga.md"
  - ğŸ“–Books: "Books.md"
  - ğŸ˜¼Anime: "Anime.md"

extra_css:
  - stylesheets/extra.css
