site_name: Piracy Link Archive
copyright: Made by Zenith Rifle and Vran29. Huge thanks to fmhy!
site_url: https://pla.fr.to

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://eason.cloud
theme:
  features:
    - navigation.top
    - navigation.sections
  name: material
  icon:
    logo: material/pirate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

nav:
  - ğŸ´â€â˜ ï¸Home: "index.md"
  - ğŸ¬Movies: "Movies.md"
  - ğŸ“ºTV Shows: "TV-Shows.md"
  - ğŸ§Music: "Music.md"
  - ğŸ®Games: "Games.md"
  - ğŸ’½Software: "Software.md"
  - ğŸ“šComics: "Comics.md"
  - ğŸï¸Manga: "Manga.md"
  - ğŸ“–Books: "Books.md"
  - ğŸ˜¼Anime: "Anime.md"

extra_css:
  - stylesheets/extra.css


repo_url: https://github.com/ashiccloud/piracylinkarchive.git

plugins:
  - search
  - git-revision-date-localized
  - social:
      cards_layout: default
      cards_layout_options:
        background_image: layouts/Untitled.png